version: "3"

services:
  n1kko777-dev:
    container_name: n1kko777-dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=n1kko777-dev.ru,www.n1kko777-dev.ru
      - LETSENCRYPT_HOST=n1kko777-dev.ru,www.n1kko777-dev.ru
      - LETSENCRYPT_EMAIL=webmaster@n1kko777-dev.ru
    restart: unless-stopped
    ports:
      - "3000:80"

networks:
  default:
    external:
      name: proxy-bypass
